<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Btn_app.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Btn_app.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-29 10:34:39 */
/* http://harviacode.com */

 class Btn_app extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Btn_app_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl("btn_app")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('btn_name', 'Name', 'trim|xss_clean|required');
		$this->form_validation->set_rules('btn_url', 'Url', 'trim|xss_clean|required');
		$this->form_validation->set_rules('btn_icon', 'Icon', 'trim|xss_clean');
		$this->form_validation->set_rules('bg_color', 'Color', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Btn_app');
    $this->layouts->view(config_item("cpanel").'content/btn_app/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


//  function detail($id){
//     if($row=$this->model->get_where($id)){
//       $this->layouts->set_title('Btn_app');
//         $data=array('layout_title' => 'Btn_app',
// 										'id_btn' => $row->id_btn,
// 										'btn_name' => $row->btn_name,
// 										'btn_url' => $row->btn_url,
// 										'btn_icon' => $row->btn_icon,
// 										'bg_color' => $row->bg_color,
// 									);
// 				 // $this->layouts->view(config_item("cpanel").'content/btn_app/detail',array(),$data);
// //MODAL DETAIL
// //$this->layouts->view(config_item("cpanel").'content/btn_app/detail',array(),$data,false);
//     }else {
//         $this->error_404();
//     }
//   }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'btn_name' => $this->input->post('btn_name',TRUE),
																'btn_url' => $this->input->post('btn_url',TRUE),
																'btn_icon' => $this->input->post('btn_icon',TRUE),
																'bg_color' => $this->input->post('bg_color',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Btn_app');
      $data = array('layout_title' => 'Btn_app',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'btn_app/tambah/aksi'),
											'id_btn' => set_value('id_btn'),
											'btn_name' => set_value('btn_name'),
											'btn_url' => set_value('btn_url'),
											'btn_icon' => set_value('btn_icon'),
											'bg_color' => set_value('bg_color'),
											);
			 //$this->layouts->view(config_item("cpanel").'content/btn_app/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/btn_app/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'btn_name' => $this->input->post('btn_name',TRUE),
																'btn_url' => $this->input->post('btn_url',TRUE),
																'btn_icon' => $this->input->post('btn_icon',TRUE),
																'bg_color' => $this->input->post('bg_color',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Btn_app');
        $data = array('layout_title' => 'Btn_app',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'btn_app/edit/'.$id.'/aksi'),
											'id_btn' => set_value('id_btn', $row->id_btn),
											'btn_name' => set_value('btn_name', $row->btn_name),
											'btn_url' => set_value('btn_url', $row->btn_url),
											'btn_icon' => set_value('btn_icon', $row->btn_icon),
											'bg_color' => set_value('bg_color', $row->bg_color),
											);
			 //$this->layouts->view(config_item("cpanel").'content/btn_app/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/btn_app/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
