<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Pengumuman.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Pengumuman.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-10 09:51:44 */
/* http://harviacode.com */

 class Pengumuman extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Pengumuman_model','model');
      if ($this->cl->acl("pengumuman")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('pengumuman', 'pengumuman', 'trim|xss_clean|required');
		$this->form_validation->set_rules('desc', 'desc', 'trim|xss_clean|required');
		$this->form_validation->set_rules('image', 'image', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Pengumuman');
    $this->layouts->view(config_item("cpanel").'content/pengumuman/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Pengumuman');
        $data=array('layout_title' => 'Pengumuman',
										'id_pengumuman' => $row->id_pengumuman,
										'pengumuman' => $row->pengumuman,
										'desc' => $row->desc,
										'image' => $row->image,
                    'slug'  =>$row->slug,
                    'created_at'=>$row->created_at,
                    'update_at'=>$row->update_at
									);
				 $this->layouts->view(config_item("cpanel").'content/pengumuman/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/pengumuman/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'pengumuman' => $this->input->post('pengumuman',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'image' => $this->input->post('image',TRUE),
																'slug' => slug($this->input->post('pengumuman',TRUE)),
                                'created_by' => sess('id_auth'),
																'created_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Pengumuman');
      $data = array('layout_title' => 'Pengumuman',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'pengumuman/tambah/aksi'),
											'id_pengumuman' => set_value('id_pengumuman'),
											'pengumuman' => set_value('pengumuman'),
											'desc' => set_value('desc'),
											'image' => set_value('image'),
											);
			 $this->layouts->view(config_item("cpanel").'content/pengumuman/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/pengumuman/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'pengumuman' => $this->input->post('pengumuman',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'image' => $this->input->post('image',TRUE),
																'slug' => slug($this->input->post('pengumuman',TRUE)),
                                'update_by' => sess('id_auth'),
																'update_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Pengumuman');
        $data = array('layout_title' => 'Pengumuman',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'pengumuman/edit/'.$id.'/aksi'),
											'id_pengumuman' => set_value('id_pengumuman', $row->id_pengumuman),
											'pengumuman' => set_value('pengumuman', $row->pengumuman),
											'desc' => set_value('desc', $row->desc),
											'image' => set_value('image', $row->image),
											'slug' => set_value('slug', $row->slug),
											'created_by' => set_value('created_by', $row->created_by),
											'created_at' => set_value('created_at', $row->created_at),
											'update_by' => set_value('update_by', $row->update_by),
											'update_at' => set_value('update_at', $row->update_at),
											);
			 $this->layouts->view(config_item("cpanel").'content/pengumuman/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/pengumuman/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
