<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Prodi.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Prodi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-19 19:49:23 */
/* http://harviacode.com */

 class Prodi extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Prodi_model','model');
      if ($this->cl->acl("prodi")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_prodi', 'id_prodi', 'trim');
		$this->form_validation->set_rules('prodi', 'Program Studi', 'trim|xss_clean|required');
		$this->form_validation->set_rules('desc', 'Deskripsi', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Prodi');
    $data['row'] = $this->model->get_data()->result();
    $this->layouts->view(config_item("cpanel").'content/prodi/index',array(),$data);
  }

 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Prodi');
        $data=array('layout_title' => 'Prodi',
										'id_prodi' => $row->id_prodi,
										'prodi' => $row->prodi,
										'desc' => $row->desc,
										'slug' => $row->slug,
									);
				 $this->layouts->view(config_item("cpanel").'content/prodi/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/prodi/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'prodi' => $this->input->post('prodi',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'slug' => slug($this->input->post('prodi',TRUE)),
                                'created_by' => sess('id_auth'),
																'created_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Prodi');
      $data = array('layout_title' => 'Prodi',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'prodi/tambah/aksi'),
											'id_prodi' => set_value('id_prodi'),
											'prodi' => set_value('prodi'),
											'desc' => set_value('desc'),
											);
			 $this->layouts->view(config_item("cpanel").'content/prodi/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/prodi/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'prodi' => $this->input->post('prodi',TRUE),
																'desc' => $this->input->post('desc',TRUE),
																'slug' => slug($this->input->post('prodi',TRUE)),
                                'update_by' => sess('id_auth'),
																'update_at' => date('Y-m-d h:i:s'),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Prodi');
        $data = array('layout_title' => 'Prodi',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'prodi/edit/'.$id.'/aksi'),
											'id_prodi' => set_value('id_prodi', $row->id_prodi),
											'prodi' => set_value('prodi', $row->prodi),
											'desc' => set_value('desc', $row->desc),
											);
			 $this->layouts->view(config_item("cpanel").'content/prodi/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/prodi/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
