<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-19 20:42:30 */
/* http://harviacode.com */

 class Dosen_model extends CI_Model{
  var $table = 'dosen';
  var $id    = 'id_pegawai';

    // datatables
      function json() {
          $this->datatables->select('id_pegawai,prodi.id_prodi,prodi.prodi,nidn,nama,image');
          $this->datatables->from('dosen');
          //add this line for join
          $this->datatables->join('prodi', 'dosen.id_prodi = prodi.id_prodi','left');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."dosen/detail/$1").'" id="detail" class="btn btn-sm btn-primary">detail</a>
           <a href="'.site_url(config_item("cpanel")."dosen/edit/$1").'" id="edit" class="btn btn-sm btn-warning">edit</a>
           <a href="'.site_url(config_item("cpanel")."dosen/hapus/$1").'" id="hapus" class="btn btn-sm btn-danger">hapus</a>',
           'id_pegawai');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }

      function get_where_join($where)
        {
          return $this->db->select('id_pegawai,dosen.id_prodi,prodi,nidn,nama,image,dosen.desc')
                          ->from('dosen')
                          ->join('prodi', 'dosen.id_prodi = prodi.id_prodi','left')
                          ->where($this->id,$where)
                          ->get()
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
